baseurl = "http://www.servicemesher.com/"
title = "ServiceMesher"
theme = "hugo-universal-theme"
languageCode = "zh"
hasCJKLanguage = true
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "zh"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Code highlight
pygmentsUseClasses = false
pygmentCodeFences = true

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "主页"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "博客"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name="文档"
    identifier = "docs"
    weight = 3

[[menu.main]]
    parent="docs"
    name="Awesome"
    url = "/awesome-servicemesh/"
    weight = 1

[[menu.main]]
    parent="docs"
    name="Envoy"
    url = "/envoy/"
    weight = 2

[[menu.main]]
    parent="docs"
    name="Istio"
    url = "https://preliminary.istio.io/zh/"
    weight = 3

[[menu.main]]
    name = "活动"
    identifier = "activity"
    url  = "/activity/"
    weight = 4

[[menu.main]]
    name = "联系我们"
    url  = "/contact/"
    weight = 5
# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/servicemesher"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:jimmysong@jimmysong.io"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Jimmy Song(宋净超)"
    defaultKeywords = ["service mesh","服务网格"]
    defaultDescription = "ServiceMesher - Service Mesh技术圈"
    # Browser title description
    description = "ServiceMesher"
    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""
    # Baidu统计
    baiduKey="154337f0d95f0b110f98c1d5d7038895"
    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "violet"
    # Social share buttons
    share = true

    # 404 page
    errorimage = "https://ws1.sinaimg.cn/large/00704eQkgy1frkahxdca2j30hd08wq52.jpg"

    # Since this templateis static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "jimmysong@jimmysong.io"
    about_us = "<p>传播Service Mesh技术、加强行业内部交流、促进开源文化构建、推动Service Mesh在企业落地</p><img src=https://ws1.sinaimg.cn/large/00704eQkgy1fshv7n2uf7j303k03kweu.jpg>"
    copyright = "Copyright ©️ 2018, ServiceMesher all rights reserved."
    icpno = "京ICP备15032932号-5"
    # Format dates with Go's time formatting
    date_format = "2006年1月2日"
    logo = "https://ws1.sinaimg.cn/large/00704eQkgy1fshutb9ya0j316v09nabp.jpg"
    # avatar used for thumbnail on sharing
    avatar = "https://ws1.sinaimg.cn/large/006tNc79gy1ft0al49s2hj30go08rwfn.jpg"
    logosmall = "https://ws1.sinaimg.cn/large/00704eQkgy1fshuwshsojj30f303ewev.jpg"
    address = """<p>加我微信（请备注姓名-公司），加入微信交流群，参与社区活动</p><p><img src="https://ws1.sinaimg.cn/large/006tNc79gy1ft002et2e2j303k03k3yk.jpg"></p>
      """

[Permalinks]
    #blog = "/blog/:year/:month/:day/:filename/"
    blog = "/blog/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">ServiceMesher社区，Service Mesh人共同的家园</p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # Set carousel background image
    background = "https://ws1.sinaimg.cn/large/00704eQkgy1frlkpcfzt4j30zk0k0at2.jpg"
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "社区活动与公告"
    subtitle = "我们会不定期得在线上和线下举办精彩的活动，敬请关注，下面是活动公告"

[params.see_more]
    enable = true
    icon = "fa fa-pagelines"
    title = "参与进来"
    subtitle = "加入 Service Mesh 爱好者社区"
    link_url = "/contact"
    link_text = "查看加入方式"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "参与者"
    subtitle = "Envoy官方文档中文版卓越贡献者"

[params.recent_posts]
    enable = true
    title = "最新博客"
    subtitle = "社区参与者的博客与最 in 的新闻都在这里"

[outputs]
    home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[params.algolia]
    enable = true
    appid = "X4YB3WOBNV"
    index = "servicemesher"
    vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
    params = ["categories", "tags"]
    key = "d2134c5a8d250e6d3246594240c45201"
